print("Welcome to the tip calculator !")
total_bill = input("What was the total bill ? $")
tip = input("How much tip would you like to give ? 10, 12 or 15 ?")
people = input("How many people to split the bill ?")
bill_by_people = (float(total_bill) / int(people)) * (1+int(tip)/100)
print(f"Each person should pay : ${bill_by_people} ")